
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 684663
	#The name of the modpack
	modpackName = "Creator's Delight"
	#The version of the modpack
	modpackVersion = "2.0-b4"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

